name: Deploy Saudi Music Database
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug secrets (remove in production)
        run: |
          echo "Sheet ID length: ${#GOOGLE_SHEET_ID}"
          echo "API Key length: ${#GOOGLE_API_KEY}"
          echo "Sheet ID starts with: ${GOOGLE_SHEET_ID:0:10}..."
          echo "API Key starts with: ${GOOGLE_API_KEY:0:10}..."
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        
      - name: Replace API credentials
        run: |
          # Use | as delimiter instead of / to avoid conflicts
          sed -i "s|YOUR_GOOGLE_SHEET_ID_HERE|$GOOGLE_SHEET_ID|g" index.html
          sed -i "s|YOUR_GOOGLE_API_KEY_HERE|$GOOGLE_API_KEY|g" index.html
          
          # Verify replacement worked
          if grep -q "YOUR_GOOGLE_SHEET_ID_HERE" index.html; then
            echo "ERROR: Sheet ID replacement failed"
            exit 1
          fi
          
          if grep -q "YOUR_GOOGLE_API_KEY_HERE" index.html; then
            echo "ERROR: API Key replacement failed"
            exit 1
          fi
          
          echo "✅ Credential replacement successful"
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
